[DFS와 BFS] 10월 31일
Altu-Bitu/Altu-Bitu_Eunji pull request #16
Opened 2021-10-31 11:46 UTC by Lil2P

제출합니다!

2021-10-31 12:59 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! p1이긴 한데 아주 큰 문제는 아니예요!
그래도 잊으면 큰일날수도 있는 부분이라 체크하고 넘어갑시당

다른 소소한 코멘트들도 참고해서 수정해주실 수 있는 부분은 수정해주세요!
그나저나 저희가 이번 프로그래머스 과제에 메인을 제공안했었네요. 방금 급하게 추가했습니다. 허허 죄송합니다...

쉽지 않은 주제였는데 과제 풀어주신거 보니까 잘 이해하신 것 같네요!
수정하시고 리뷰어로 저 불러주세요!!

2021-10-31 12:59 UTC, HyunJiLim0406 commented on 10월 15일 - DFS와 BFS/1697.cpp
> +
100000라는 숫자가 많이 쓰이네요! 이건 상수로 선언해두면 가독성 면에서 더 좋아져요

2021-10-31 12:59 UTC, HyunJiLim0406 commented on 10월 15일 - DFS와 BFS/1697.cpp
> +	int time = 0;
혹시 실행하실 때 리턴값이 존재하지 않는 분기가 존재한다는 경고를 보셨을까요?
이 문제에선 당연히 line 18의 조건에 걸리는 순간이 오게 될거예요!

만약 경고가 신경쓰이신다면 마지막에 `return -1`을 하거나 line 19에서 break를 하고 마지막에 리턴을 하는 방법도 있어요!

2021-10-31 12:59 UTC, HyunJiLim0406 commented on 10월 15일 - DFS와 BFS/4963.cpp
> +void bfs(int w, int h, int r, int c, vector<vector<int>>& map) {
p1
엇 혹시 뭐 하나 빼먹은 것 같진 않으신가요?
이 문제에선 크게 문제되지 않지만 아주 중요한걸 하나 빠뜨리신 것 같아요...!
만약 의도하신거라도 되도록 항상 처리해주셔야 하는 부분이에요!

2021-10-31 12:59 UTC, HyunJiLim0406 commented on 10월 15일 - DFS와 BFS/4963.cpp
> +int main() {
이건 정말 개인 취향의 영역인데요. 전 사실 이런 문제는 dfs로 푸는 편이긴 해요 하핳
왜냐면 재귀라 코드도 짧고 스택 include 할 필요도 없고...근데 그냥 본인에게 익숙한걸로 구현하는게 제일 좋아요!

2021-10-31 12:59 UTC, HyunJiLim0406 commented on 10월 15일 - DFS와 BFS/2021카카오_거리두기.cpp
> +        int dc[4] = { 0, 0, -1, 1 };
dr과 dc가 while문을 돌때마다 초기화되겠네요! 불필요한 초기화를 줄이려면 어떻게 수정하는게 좋을까요?

2021-10-31 12:59 UTC, HyunJiLim0406 commented on 10월 15일 - DFS와 BFS/2021카카오_거리두기.cpp
> +                else if (place[nr][nc] == 'O') { //�� ���̶��
if문에 걸리면 무조건 리턴하게 되네요. 그럼 어떻게 수정할 수 있나요?

2021-10-31 12:59 UTC, HyunJiLim0406 commented on 10월 15일 - DFS와 BFS/2021카카오_거리두기.cpp
> +bool bfs(int row, int col, vector<string>place) { //row, col: ����� �ġ
별건 아닌데 place를 그냥 넘기면 복사해서 넘겨지니까 앞에 &를 붙이면 더 좋아요!
그나저나 bfs 함수 정말 잘 작성하셨네요!

2021-10-31 12:59 UTC, HyunJiLim0406 commented on 10월 15일 - DFS와 BFS/2021카카오_거리두기.cpp
> +            if (!checkDistance(j, places[i])) { //�Ÿ��α⸦ ��Ű�� �ʰ� �ִٸ�
행은 여기에서 검사하고 열은 checkDistance에서 검사하는 것 같네요. 강의실별로 분리되고 행과 열은 함께 검사하는게 더 좋지 않을까요...! 😃

2021-11-01 03:08 UTC, Lil2P commented
섬의 개수 DFS로 풀어본 것도 올렸습니다!
늘 감사합니다 :)

2021-11-01 03:35 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 제가 말씀드린 부분들 잘 수정해주시고 DFS 풀이도 해주셨네요!!
다만 제가 4963번은 약간 오해의 소지가 생기게 코멘트를 했었군요,,, 다시 코멘트 달았으니까 확인해주세요!

그나저나 지난 리뷰에서 말씀드리려고 했는데 주석을 꼼꼼하게 달아주셔서 리뷰하기 편했어요 감사합니다...!
4963번에 제가 달아놓은 코멘트 부분만 수정하시고 바로 머지하셔도 됩니다!

2021-11-01 03:35 UTC, HyunJiLim0406 commented on 10월 15일 - DFS와 BFS/4963.cpp
> +	while (!q.empty()) {
앗 제가 코멘트를 선언부에 달아서 오해하시게 만들었군요 죄송합니다,,,
사실 이 함수 안에서 찾아보시란 뜻에서 그렇게 한거였는데 앞으론 그런 경우에 제대로 명시할게요!
이 함수의 문제점은 시작점의 방문처리를 하지 않는거였어요!

그럼 시작 정점을 방문처리 하지 않았음에도 불구하고 왜 맞았습니다를 받았을까요? 간단한 문제니까 한 번 고민해보셔도 좋아요!
그래프 탐색시엔 방문처리 꼭 해주세요~!! 😉

2021-11-01 03:35 UTC, HyunJiLim0406 commented on 10월 15일 - DFS와 BFS/4963_recursion.cpp
> +void dfsRecur(int r, int c) {
완벽합니다!

2021-11-01 04:09 UTC, merged