[백트래킹] 9월 30일
Altu-Bitu/Altu-Bitu_Eunji pull request #9
Opened 2021-09-29 15:27 UTC by Lil2P

제출합니다!

2021-09-29 16:23 UTC, bsa0322 requested changes
p1. 전체적으로 너무 잘 풀어주셨어요! 주석이 특히 자세해서 너무 좋았어요. 2529번만 조금 더 수정해서 저 다시 리뷰어로 호출해주세욥! 수고하셨습니다~!!!

2021-09-29 16:23 UTC, bsa0322 commented on 9월 24일 - 백트래킹/10971.cpp
> +		}
p2. 아주 잘 풀어주셨어요! 처음 방문 시에 대한 처리만 다른거니, main에서 아예 첫 방문에 대한 연산을 처리하고 백트래킹 함수로 보내줘도 좋을 것 같아요~!

2021-09-29 16:23 UTC, bsa0322 commented on 9월 24일 - 백트래킹/15665.cpp
> +set<int> inputs; //����ڰ� �Է��� �� ������ ��
중복으로 들어오는 수를 set으로 아주 잘 걸러주셨네요!! 👍👍👍 
이 문제는 백트래킹 함수 내에서 중복을 처리하는 방법의 풀이도 있어요. 한 번 생각해봐도 좋을 것 같아요!

2021-09-29 16:23 UTC, bsa0322 commented on 9월 24일 - 백트래킹/2529.cpp
> +		}
p2. 이 부분 38번째 조건을 잘 설정하면 cnt == 0 따로 처리할 필요 없이 합칠 수 있을 것 같아요!

2021-09-29 16:23 UTC, bsa0322 commented on 9월 24일 - 백트래킹/2529.cpp
> +vector<string> result; //�ε�ȣ ����ϴ� ��� �� ������ �迭
p1. 이 문제는 꼭 모든 수를 저장하지 않고도, 바로 최솟값과 최댓값을 구할 수 있어요!
길이는 k로 고정이고, 수는 0\~9까지 사용이 가능하죠. 최솟값은 어떤 수로 이루어지고, 최댓값은 어떤 수로 이루어지는지를 생각해보시면 해결하실 수 있을 거에요! 이렇게 풀면 시간도 훨씬 단축돼요! 
수정 후, 저 다시 리뷰어로 호출해주세요! 수고하셨습니다~!!

2021-09-30 11:41 UTC, Lil2P commented
일단 나름대로 수정해보았습니다!
사정이 있어 늦은 점 정말 죄송합니다 ㅠㅠ

2021-09-30 11:44 UTC, Lil2P commented
15665번의 경우 함수 내에서 중복을 처리하는 방법을 고민해봤는데 코드가 너무 지저분해져서 좀 더 고민해본 후, 나중에 샘플 코드가 올라오면 비교해보도록 하겠습니다!

2021-09-30 14:45 UTC, bsa0322 approved these changes
p2. 아고 저야말로 확인이 늦어졌네요 ㅜㅜ 외판원 순회 문제도 깔끔하게 잘 해주셨고, 부등호 문제도 아주 좋아요! 아주 조금 더 좋아질 수 있어서 코멘트 추가했어요. 넘 수고하셨습니다! 머지해주셔도 괜찮아요~!

2021-09-30 14:45 UTC, bsa0322 commented on 9월 24일 - 백트래킹/10971.cpp
> +	}
👍👍👍

2021-09-30 14:45 UTC, bsa0322 commented on 9월 24일 - 백트래킹/2529.cpp
> +		}
p2. 꼭 필요할까요? 0 ~ k까지의 수로 처음 만들어지는 수가 결국 어떻게 되는지 생각해볼까요?

2021-09-30 14:45 UTC, bsa0322 commented on 9월 24일 - 백트래킹/2529.cpp
> +		}
p2. 여기도 마찬가지에요!

2021-10-01 05:46 UTC, merged